In [1]:
import cv2
import numpy as np

In [2]:
img=cv2.imread(r"F:\CV\Code\Data\avengers.jpg")
img=cv2.resize(img, (500,300))
cv2.imshow('img', img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
print(img)

[[[ 28  28  28]
  [ 25  23  23]
  [ 28  23  24]
  ...
  [ 37  33  38]
  [ 38  35  40]
  [ 38  34  39]]

 [[ 21  21  21]
  [ 26  24  24]
  [ 24  19  20]
  ...
  [ 33  29  34]
  [ 37  33  38]
  [ 31  27  32]]

 [[ 18  18  18]
  [ 19  17  17]
  [ 23  18  19]
  ...
  [ 33  29  34]
  [ 31  26  32]
  [ 33  29  34]]

 ...

 [[ 54  89 198]
  [ 59  93 215]
  [ 76 135 243]
  ...
  [ 52 101 202]
  [ 61 108 205]
  [ 71 119 198]]

 [[ 48  92 207]
  [ 66 119 234]
  [ 86 157 255]
  ...
  [ 53 104 211]
  [ 63 117 212]
  [ 76 131 212]]

 [[ 82 106 193]
  [104 145 223]
  [118 175 236]
  ...
  [ 86 122 194]
  [ 96 138 200]
  [106 146 205]]]


In [8]:
img=cv2.imread(r"F:\CV\Code\Data\lady.jpg")
img=cv2.resize(img, (300,300))
h=np.hstack((img,img))
v=np.vstack((img,img))
v1=np.vstack((h,h))
cv2.imshow('img', h)
cv2.imshow('img1',v)
cv2.imshow('mul',v1)
cv2.waitKey(0)
cv2.destroyAllWindows()